### ISSUE TITLE
How to visualize the style features ?

### ISSUE THREAD

**Issue by vikiboy** [robertomest/neural-style-keras#1]
Is there a way to display the style features like the ones shown in Fig. 1 of the original "A Neural Algorithm of Artistic Style" paper ( Style Reconstructions ‘conv5 1’ (e) ) ?

I guess it has got something to do with modifying the gram matrices, but I am unable to find a way to visualize them the same way as the paper does ?

**Comment by robertomest** [comment]
Hello @vikiboy , if I'm not mistaken those are the images obtained using the iterative method when you have no content image, i.e., you are only trying to reproduce style. You could obtain images similar to those but running the iterative_style_transfer script with a very small weight for the content loss (`--content_weight 0`). In this case, the content image you choose does not really matter, since the optimziation procedure is not trying to minimize the content loss.
Each of those images are obtained with different layers being part of the style loss, you can choose which layers you would like to use with the `--style_layers` parameter. In the case of item (e), the default value should be adequate. Let me know if this helps.

**Comment by vikiboy** [comment]
Hey, I tried that, and it works. Basically the content image directs the shape of the output image, without contributing to the style of the target image. Thanks 👍
